### PR TITLE
Add support for VS2019

### PR DESCRIPTION
**Pull request by jmarrec**
Copied then Upgraded the vs2017 solution (and vcxproj) to with VS2019.

### CODE REVIEW

**Comment by AaronDMarasco-VSI** [comment]
@jmarrec I'm pretty sure this is a read-only mirror of the `xz` project; you would need to contact the author(s) at https://tukaani.org/xz/ for code contribution.

**Comment by jmarrec** [comment]
I figured as well given the name (mirror...) but being unfamiliar with collaboration on sourceforge I popped by IRC and upon lack of immediate response I opened this PR.

I'll see if this is picked up otherwise I will send an email.

**Comment by simnalamburt** [comment]
When I contacted Lasse Collin a few years ago, IRC was the best way. If he does not use IRC these days, it is probably best to contact him via email.

At least I'm pretty mush sure that Lasse Collin will not see the GitHub PR since he doesn't even have GitHub account.

I hope your patch can be merged.

##### Reference
- https://tukaani.org/contact.html

**Comment by simnalamburt** [comment]
@jmarrec Congretulation! Looks like you successfully merged the patch you want! Thanks for contributing the xz prohect :)

**Pull request closed without merging**
