### PR TITLE
Manpages

### PR DESCRIPTION
**Pull request by mariobl**
I've created a framework for the internationalization of man pages. It works as follows:

As a prerequisite, the po4a tools are needed, see [1].
 
The script create-translation-template.sh updates the translation template named xz-man.pot from all man pages in the subdirectories of src/ (currently it contains 638 gettext messages).
A German translation (de.po) is already included. Other po files (which will hopefully arrive in the future) also need to be placed in src/, and the language code needs to be added in the [po4a_langs] line in po4a.conf. Then run the script create-translated-manpages.sh (or simply "po4a po4a.conf") to create the translated man pages. The Groff files will be placed in the subdirectories of src/, where the English man pages reside. If needed, the storage location can be changed in po4a.conf.

Unfortunately, I have no experience with GNU Autotools, I'm just a translator, and no more than that. I don't know how to integrate the contents of my scripts with "configure" and the existing m4 macros.

Once it works, xz needs a second translation domain at GNU TP.

### CODE REVIEW

**Comment by mariobl** [comment]
> As a prerequisite, the po4a tools are needed, see [1].
[1] https://po4a.org/index.php

**Comment by simnalamburt** [comment]
Hi I'm quite greatful to see someone who actually contributed to xz project. But sadly any commit that I merge to this mirror repo will be overwritten by upstream repo (=actual xz repo). You should contact to the Lasse Collin via IRC or email instead. https://tukaani.org/contact.html

I hope someday Lasse Collin will move the xz project to GitHub.

**Comment by mariobl** [comment]
> Hi I'm quite greatful to see someone who actually contributed to xz project. But sadly any commit that I merge to this mirror repo will be overwritten by upstream repo (=actualy xz repo). You should contact to the Lasse Collin via IRC or email instead. https://tukaani.org/contact.html
> 
How do you commit your changes? If you don't have direct write access to this mirror, you need to create your own fork and submit your changes via a merge request. But I don't see any open merge requests for the time being.

> I hope someday Lasse Collin will move the xz project to GitHub.

As long as mirroring works (and obviously it does, the git repo at tukaani.org [1] is in sync with this mirror) I'm fine with it if Lasse keeps a main repo and provides a mirror here for external contributors.

[1] https://git.tukaani.org/?p=xz.git;a=summary

**Comment by simnalamburt** [comment]
I am owner of this mirror repo right, but there's an automated script called [xz-mirror] which periodically fetch commits from <https://git.tukaani.org/?p=xz.git> and force push to here so every change that we apply to here will be overwritten in one day.

So you should push your commits to the original <https://git.tukaani.org/?p=xz.git> repo, and you must contact Lasse Collin to do so since Lasse Collin is the owner of that original repo.

[xz-mirror]: https://github.com/xz-mirror/xz-mirror

**Comment by mariobl** [comment]
> I am owner of this mirror repo right, but there's an automated script called [xz-mirror](https://github.com/xz-mirror/xz-mirror) which periodically fetch commits from https://git.tukaani.org/?p=xz.git and force push to here so every change that we apply to here will be overwritten in one day.
>
It's completely the wrong way to setup a mirror here without agreement of (and collaboration with) the owner of the original repo. If you do so, you must not expect that things work… Moreover, it is urgently needed to mark this mirror as unofficial.

> So you should push your commits to the original https://git.tukaani.org/?p=xz.git repo, and you must contact Lasse Collin to do so since Lasse Collin is the owner of that original repo.

Yes, I will do so.

**Comment by simnalamburt** [comment]
@mariobl 

I did setup this mirror **with** agreement of Lasse Collin. This mirror is only read-only because he did not show his intention to move the project to the GitHub.

Best regards,
Hyeon Kim

**Comment by mariobl** [comment]
A _read only_ mirror is _not_ a mirror, it's no more than a copy. You should add this information to the description of your repo, to avoid double work. If Lasse has decided to **not** to move to Github, it's OK for me, nobody can force him to do so. Well it would be easier to submit my changes, but it works also with `git diff`.

**Comment by simnalamburt** [comment]
I'm afraid that most people agree with a concept that "read only mirror is mirror".

https://github.com/gcc-mirror/gcc
https://github.com/llvm-mirror/llvm
https://github.com/ghc/ghc
https://github.com/freebsd/freebsd

There were a few people who opened PR to this repo earlier and they agreed with "read only mirror is mirror" too. https://github.com/xz-mirror/xz/pull/1

Anyway I hope your patch can be merged into upstream. It's not easy to find someone who want to contribute to XZUtils nowaday.

**Comment by mariobl** [comment]
If there's no way to get my changes into the original repo, then it doesn't make sense for me. For viewing purposes only, I can use the Git at tukaani.org. A mirror needs to work in both ways: forth and back. Changes in the origin need to land in the mirror as fast as possible, and also vice versa. This is also described in the Github docs [1]. A one way mirror doesn't make sense for me.

[1] https://help.github.com/en/articles/about-github-mirrors

**Comment by simnalamburt** [comment]
The repositories listed in page <https://help.github.com/en/articles/about-github-mirrors> is mostly one-way read-only mirror.

And actually, you brought up the very good point. This mirror was created because git.tukaani.org server was very unstable and didn't support HTTPS in a long time ago. I once tried to develop [Rust] binding of liblzma, and I found those very uncomfortable so I made this mirror.

Now we might not need this mirror but many people including me prefer GitHub UI than cgit UI so I'll continue maintain this mirror.

[Rust]: https://www.rust-lang.org/

**Comment by simnalamburt** [comment]
Anyway thank you for contributing the XZUtils and I have no hard feelings about weather a mirror should be writable or not. Have a nice day :)

**Pull request closed without merging**
